# Política de Crédito

## 1. Imports e Configurações

In [ ]:
import sys
from pathlib import Path
sys.path.append(str(Path('..').resolve()))

import os
import pickle

import numpy as np
import pandas as pd

from src.eda import calculate_information_value
from src.feature_selection import *

## 2. Dicionário de Tipos

In [2]:
with open(
    r"../outputs/dicts/tipos_var.pkl",
    "rb"
) as f:

    tipos_var = pickle.load(f)

display(tipos_var)

{'key': ['id_cliente', 'safra_mes'],
 'binary': ['possui_carro', 'possui_imovel', 'sexo_masculino'],
 'categorical': [],
 'integer': ['qtd_filhos',
  'qtd_membros_familia',
  'qtd_contratos_aceitos_historico',
  'qtd_contratos_recusados_historico',
  'nota_regiao_cliente',
  'nota_regiao_cliente_cidade',
  'idade'],
 'numeric': ['valor_bem_submissao',
  'media_valor_credito_aceito_historico',
  'soma_valor_credito_ativo_historico',
  'valor_credito_submissao',
  'valor_parcela_submissao',
  'renda_anual',
  'tipo_contrato_submissao_woe',
  'dia_semana_solicitacao_submissao_woe',
  'hora_solicitacao_submissao_woe',
  'estado_civil_woe',
  'tipo_renda_woe',
  'tipo_organizacao_woe',
  'tipo_moradia_woe',
  'nivel_educacao_woe'],
 'datetime': [],
 'target': 'target'}

## 3. Carregamento das Bases

In [3]:
train_rus = pd.read_parquet("../data/processed/train_rus_model.parquet")
oos = pd.read_parquet("../data/processed/oos_model.parquet")
oot = pd.read_parquet("../data/processed/oot_model.parquet")

print(train_rus.shape)
print(oos.shape)
print(oot.shape)

(814, 27)
(12383, 27)
(19970, 27)

## 4. Separação de Features

In [4]:
TARGET = tipos_var["target"]

features = [
    c
    for c in (
        tipos_var["binary"]
        + tipos_var["integer"]
        + tipos_var["numeric"]
    )
    if c in train_rus.columns
]

print(f"{len(features)} variáveis")

24 variáveis

## 5. Variance Inflation Factor (VIF)

In [5]:
features_vif, vif_final = vif_selection(
    train_rus[features],
    threshold=10
)

display(vif_final)
print(f"Número de variáveis selecionadas: {len(features_vif)}")

================================================================================
Iteração 1
================================================================================

                                variavel          vif
0         hora_solicitacao_submissao_woe  1082.607059
1                valor_credito_submissao    32.488858
2                    valor_bem_submissao    29.228445
3             nota_regiao_cliente_cidade     9.712356
4                    nota_regiao_cliente     9.539611
5     soma_valor_credito_ativo_historico     7.657123
6   media_valor_credito_aceito_historico     6.178056
7                    qtd_membros_familia     4.739773
8                             qtd_filhos     4.460786
9                valor_parcela_submissao     3.799319
10       qtd_contratos_aceitos_historico     3.450992
11           tipo_contrato_submissao_woe     1.741733
12                                 idade     1.576108
13                        tipo_renda_woe     1.329136
14                           renda_anual     1.250007
15                      estado_civil_woe     1.246488
16                        sexo_masculino     1.239441
17                          possui_carro     1.220255
18     qtd_contratos_recusados_historico     1.205629
19                    nivel_educacao_woe     1.089274
20                  tipo_organizacao_woe     1.057115
21                      tipo_moradia_woe     1.051979
22                         possui_imovel     1.042150
23  dia_semana_solicitacao_submissao_woe     1.025916

Removendo: hora_solicitacao_submissao_woe (VIF=1082.61)

================================================================================
Iteração 2
================================================================================

                                variavel         vif
0                         tipo_renda_woe  311.711065
1                     nivel_educacao_woe  251.130046
2                       tipo_moradia_woe  111.989672
3                   tipo_organizacao_woe   74.098986
4             nota_regiao_cliente_cidade   57.932797
5                    nota_regiao_cliente   56.452542
6                valor_credito_submissao   52.627714
7                    valor_bem_submissao   47.940590
8                    qtd_membros_familia   12.646343
9   media_valor_credito_aceito_historico   12.044503
10    soma_valor_credito_ativo_historico   11.940085
11               valor_parcela_submissao    8.274946
12                                 idade    6.495804
13                      estado_civil_woe    6.462292
14       qtd_contratos_aceitos_historico    6.179066
15                            qtd_filhos    5.823898
16           tipo_contrato_submissao_woe    4.963010
17                           renda_anual    3.855051
18                         possui_imovel    3.352434
19  dia_semana_solicitacao_submissao_woe    2.282022
20                        sexo_masculino    1.834504
21                          possui_carro    1.775521
22     qtd_contratos_recusados_historico    1.403910

Removendo: tipo_renda_woe (VIF=311.71)

================================================================================
Iteração 3
================================================================================

                                variavel         vif
0                     nivel_educacao_woe  139.048759
1                       tipo_moradia_woe   93.942037
2                   tipo_organizacao_woe   67.735591
3             nota_regiao_cliente_cidade   57.908252
4                    nota_regiao_cliente   56.452489
5                valor_credito_submissao   52.275782
6                    valor_bem_submissao   47.908463
7                    qtd_membros_familia   12.586624
8     soma_valor_credito_ativo_historico   11.903717
9   media_valor_credito_aceito_historico   11.890015
10               valor_parcela_submissao    8.222541
11                      estado_civil_woe    6.417491
12                                 idade    6.271977
13       qtd_contratos_aceitos_historico    6.167650
14                            qtd_filhos    5.816475
15           tipo_contrato_submissao_woe    4.960196
16                           renda_anual    3.855006
17                         possui_imovel    3.352268
18  dia_semana_solicitacao_submissao_woe    2.280699
19                        sexo_masculino    1.827598
20                          possui_carro    1.772066
21     qtd_contratos_recusados_historico    1.401480

Removendo: nivel_educacao_woe (VIF=139.05)

================================================================================
Iteração 4
================================================================================

                                variavel        vif
0             nota_regiao_cliente_cidade  57.728328
1                       tipo_moradia_woe  57.283829
2                    nota_regiao_cliente  56.451989
3                valor_credito_submissao  52.180801
4                   tipo_organizacao_woe  51.921144
5                    valor_bem_submissao  47.681865
6                    qtd_membros_familia  12.580838
7     soma_valor_credito_ativo_historico  11.875361
8   media_valor_credito_aceito_historico  11.742783
9                valor_parcela_submissao   8.202342
10                      estado_civil_woe   6.342759
11                                 idade   6.266076
12       qtd_contratos_aceitos_historico   6.142141
13                            qtd_filhos   5.814720
14           tipo_contrato_submissao_woe   4.868755
15                           renda_anual   3.755930
16                         possui_imovel   3.335651
17  dia_semana_solicitacao_submissao_woe   2.267808
18                        sexo_masculino   1.827597
19                          possui_carro   1.771560
20     qtd_contratos_recusados_historico   1.401391

Removendo: nota_regiao_cliente_cidade (VIF=57.73)

================================================================================
Iteração 5
================================================================================

                                variavel        vif
0                       tipo_moradia_woe  57.278670
1                valor_credito_submissao  52.021850
2                   tipo_organizacao_woe  51.760940
3                    valor_bem_submissao  47.681030
4                    qtd_membros_familia  12.532873
5     soma_valor_credito_ativo_historico  11.771743
6   media_valor_credito_aceito_historico  11.736975
7                valor_parcela_submissao   8.097250
8                       estado_civil_woe   6.328223
9                                  idade   6.260766
10                   nota_regiao_cliente   6.208095
11       qtd_contratos_aceitos_historico   6.123999
12                            qtd_filhos   5.797015
13           tipo_contrato_submissao_woe   4.868722
14                           renda_anual   3.748274
15                         possui_imovel   3.333903
16  dia_semana_solicitacao_submissao_woe   2.267015
17                        sexo_masculino   1.824381
18                          possui_carro   1.771374
19     qtd_contratos_recusados_historico   1.398087

Removendo: tipo_moradia_woe (VIF=57.28)

================================================================================
Iteração 6
================================================================================

                                variavel        vif
0                valor_credito_submissao  51.995827
1                    valor_bem_submissao  47.530451
2                   tipo_organizacao_woe  24.766537
3                    qtd_membros_familia  12.520086
4     soma_valor_credito_ativo_historico  11.735652
5   media_valor_credito_aceito_historico  11.729963
6                valor_parcela_submissao   7.835194
7                       estado_civil_woe   6.293629
8                    nota_regiao_cliente   6.116799
9        qtd_contratos_aceitos_historico   6.052508
10                            qtd_filhos   5.792694
11                                 idade   5.585587
12           tipo_contrato_submissao_woe   4.768177
13                           renda_anual   3.704577
14                         possui_imovel   3.308953
15  dia_semana_solicitacao_submissao_woe   2.262955
16                        sexo_masculino   1.823057
17                          possui_carro   1.769835
18     qtd_contratos_recusados_historico   1.397905

Removendo: valor_credito_submissao (VIF=52.00)

================================================================================
Iteração 7
================================================================================

                                variavel        vif
0                   tipo_organizacao_woe  24.703318
1                    qtd_membros_familia  12.502837
2     soma_valor_credito_ativo_historico  11.708457
3   media_valor_credito_aceito_historico  11.427672
4                    valor_bem_submissao   8.125634
5                valor_parcela_submissao   7.727784
6                       estado_civil_woe   6.293283
7                    nota_regiao_cliente   6.116366
8        qtd_contratos_aceitos_historico   6.052184
9                             qtd_filhos   5.791406
10                                 idade   5.557032
11           tipo_contrato_submissao_woe   4.707257
12                           renda_anual   3.701380
13                         possui_imovel   3.308684
14  dia_semana_solicitacao_submissao_woe   2.258303
15                        sexo_masculino   1.819384
16                          possui_carro   1.763475
17     qtd_contratos_recusados_historico   1.397794

Removendo: tipo_organizacao_woe (VIF=24.70)

================================================================================
Iteração 8
================================================================================

                                variavel        vif
0                    qtd_membros_familia  12.330465
1     soma_valor_credito_ativo_historico  11.060442
2   media_valor_credito_aceito_historico  10.915033
3                    valor_bem_submissao   8.125554
4                valor_parcela_submissao   7.524399
5                       estado_civil_woe   5.827478
6                             qtd_filhos   5.777842
7        qtd_contratos_aceitos_historico   5.542944
8                                  idade   5.235737
9                    nota_regiao_cliente   5.116949
10           tipo_contrato_submissao_woe   3.845553
11                           renda_anual   3.563557
12                         possui_imovel   3.101021
13  dia_semana_solicitacao_submissao_woe   2.212887
14                        sexo_masculino   1.801157
15                          possui_carro   1.761088
16     qtd_contratos_recusados_historico   1.393305

Removendo: qtd_membros_familia (VIF=12.33)

================================================================================
Iteração 9
================================================================================

                                variavel        vif
0     soma_valor_credito_ativo_historico  11.028231
1   media_valor_credito_aceito_historico  10.821573
2                    valor_bem_submissao   8.123900
3                valor_parcela_submissao   7.515968
4        qtd_contratos_aceitos_historico   5.532243
5                                  idade   5.221080
6                    nota_regiao_cliente   5.070987
7                       estado_civil_woe   4.632333
8            tipo_contrato_submissao_woe   3.823834
9                            renda_anual   3.563267
10                         possui_imovel   3.098971
11  dia_semana_solicitacao_submissao_woe   2.204328
12                        sexo_masculino   1.797389
13                          possui_carro   1.742736
14                            qtd_filhos   1.546010
15     qtd_contratos_recusados_historico   1.392636

Removendo: soma_valor_credito_ativo_historico (VIF=11.03)

================================================================================
Iteração 10
================================================================================

                                variavel       vif
0                    valor_bem_submissao  7.883567
1                valor_parcela_submissao  7.512174
2   media_valor_credito_aceito_historico  6.668908
3                                  idade  5.145164
4                    nota_regiao_cliente  5.023208
5                       estado_civil_woe  4.597985
6            tipo_contrato_submissao_woe  3.823098
7                            renda_anual  3.535883
8                          possui_imovel  3.098629
9        qtd_contratos_aceitos_historico  2.334092
10  dia_semana_solicitacao_submissao_woe  2.199945
11                        sexo_masculino  1.793648
12                          possui_carro  1.741370
13                            qtd_filhos  1.544992
14     qtd_contratos_recusados_historico  1.386788

Todos os VIFs estão abaixo de 10.

                                variavel       vif
0                    valor_bem_submissao  7.883567
1                valor_parcela_submissao  7.512174
2   media_valor_credito_aceito_historico  6.668908
3                                  idade  5.145164
4                    nota_regiao_cliente  5.023208
5                       estado_civil_woe  4.597985
6            tipo_contrato_submissao_woe  3.823098
7                            renda_anual  3.535883
8                          possui_imovel  3.098629
9        qtd_contratos_aceitos_historico  2.334092
10  dia_semana_solicitacao_submissao_woe  2.199945
11                        sexo_masculino  1.793648
12                          possui_carro  1.741370
13                            qtd_filhos  1.544992
14     qtd_contratos_recusados_historico  1.386788

Número de variáveis selecionadas: 15

## 6. Correlação

In [6]:
corr_matrix = (
    train_rus[features_vif]
    .corr()
    .abs()
)

features_corr = correlation_selection(
    train_rus[features_vif],
    threshold=0.80
)

features_corr = [
    f
    for f in features_vif
    if f in features_corr
]

================================================================================
Iteração 1

Pares encontrados:

                  var1                                  var2      corr
0  valor_bem_submissao  media_valor_credito_aceito_historico  0.828756
1  valor_bem_submissao               valor_parcela_submissao  0.822952

Frequência:

                               variavel  frequencia
0                   valor_bem_submissao           2
1  media_valor_credito_aceito_historico           1
2               valor_parcela_submissao           1

Removendo: valor_bem_submissao

Todas as correlações estão abaixo de 0.8

In [7]:
print(f"Número de variáveis selecionadas: {len(features_corr)}")

Número de variáveis selecionadas: 14

## 7. Information Value (IV)

remoção de multicolinearidade via VIF e redução de redundância por correlação, será realizada uma análise do poder preditivo individual das variáveis utilizando o Information Value (IV).

In [10]:
iv_report = calculate_information_value(
    train_rus[
        features_corr + [TARGET]
    ],
    tipos_var
)

display(iv_report)

                                variavel      iv classificacao
0                            renda_anual  0.0860      Moderado
1        qtd_contratos_aceitos_historico  0.0758      Moderado
2   dia_semana_solicitacao_submissao_woe  0.0654      Moderado
3                valor_parcela_submissao  0.0482         Fraco
4                                  idade  0.0325         Fraco
5      qtd_contratos_recusados_historico  0.0265         Fraco
6   media_valor_credito_aceito_historico  0.0241         Fraco
7                       estado_civil_woe  0.0157         Fraco
8                             qtd_filhos  0.0064   Muito Fraco
9            tipo_contrato_submissao_woe  0.0034   Muito Fraco
10                        sexo_masculino  0.0033   Muito Fraco
11                   nota_regiao_cliente  0.0024   Muito Fraco
12                         possui_imovel  0.0023   Muito Fraco
13                          possui_carro  0.0000   Muito Fraco

## 8. Salva Artefatos

As variáveis identificadas após os processos de remoção de multicolinearidade (VIF) e correlação foram armazenadas em um artefato separado. Essas variáveis representam um conjunto otimizado para modelos lineares, especialmente Regressão Logística. Entretanto, a base de dados original não será modificada nesta etapa, permitindo que modelos não lineares, como Random Forest, XGBoost e LightGBM, sejam treinados utilizando o conjunto completo de variáveis, uma vez que tais algoritmos não exigem a remoção prévia de variáveis correlacionadas.

In [12]:
os.makedirs(
    "outputs/dicts",
    exist_ok=True
)

with open(
    "../outputs/dicts/features_corr.pkl",
    "wb"
) as f:

    pickle.dump(
        features_corr,
        f
    )

## 9. Conclusão

Neste notebook foi realizada a etapa de seleção e avaliação das variáveis candidatas à modelagem, com foco na redução de redundâncias e no controle de multicolinearidade.

Inicialmente, foi aplicada a análise de Variance Inflation Factor (VIF), permitindo identificar e remover variáveis com elevado grau de dependência linear em relação às demais. Em seguida, foi realizada uma análise iterativa de correlação, removendo variáveis altamente correlacionadas até que todas as correlações remanescentes estivessem abaixo do limite estabelecido.

Após essas etapas, foi calculado o Information Value (IV) das variáveis selecionadas com o objetivo de avaliar individualmente seu poder discriminatório em relação à inadimplência. Nesta fase, o IV foi utilizado apenas como uma métrica de análise e interpretação, não sendo empregado como critério de exclusão de variáveis.

Como resultado, foi obtido um conjunto de variáveis com menor redundância de informação e menor risco de multicolinearidade, especialmente adequado para modelos lineares como Regressão Logística. Esse conjunto foi armazenado em artefatos próprios para utilização posterior durante a etapa de modelagem.

É importante destacar que as remoções realizadas neste notebook não foram aplicadas diretamente às bases de dados finais. Dessa forma, os modelos não lineares poderão ser treinados utilizando todas as variáveis disponíveis, enquanto os modelos lineares poderão utilizar o conjunto reduzido selecionado nesta etapa.

Os artefatos gerados serão utilizados no próximo notebook, dedicado ao treinamento, validação e comparação dos modelos preditivos de risco de crédito.